"""empty message

Revision ID: 074b22063b7a
Revises: baf3d07c8d75
Create Date: 2022-05-06 16:08:51.455523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074b22063b7a'
down_revision = 'baf3d07c8d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailaddress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('emails', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailaddress')
    # ### end Alembic commands ###
