"""empty message

Revision ID: baf3d07c8d75
Revises: c2b8b00cb166
Create Date: 2022-04-14 16:08:02.689702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf3d07c8d75'
down_revision = 'c2b8b00cb166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_body', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('email_body')

    # ### end Alembic commands ###
